"""
Constants untuk GLRC Application
"""

# Material Icons Mapping
ICON_SETTINGS = "\ue8b8"
ICON_INFO = "\ue88e"
ICON_LOGOUT = "\ue879"
ICON_USER = "\ue7fd"
ICON_VISIBILITY = "\ue8f4"
ICON_VISIBILITY_OFF = "\ue8f5"
ICON_SEARCH = "\ue8b6"
ICON_RESET = "\ue5c9"
ICON_EXPORT = "\ue161"
ICON_IMPORT = "\ue2c8"
ICON_CHECK_ALL = "\ue86c"
ICON_UNCHECK_ALL = "\ue835"
ICON_LOGS = "\ue86f"
ICON_OPEN_IN_NEW = "\ue89f"
ICON_CLOUD_DONE = "\ue2c0"
ICON_CLOUD = "\ue2bd"
ICON_COPY = "\ue14d"
ICON_WORLD = "\ue894"

# Window Dimensions
DEFAULT_LOGIN_WIDTH = 720
DEFAULT_LOGIN_HEIGHT = 560
DEFAULT_EXPANDED_WIDTH = 960
DEFAULT_EXPANDED_HEIGHT = 840

# Pagination & Operation Limits
DEFAULT_PER_PAGE = 20
MAX_CONCURRENT_CLONES = 5
MAX_RETRY_ATTEMPTS = 3
RETRY_DELAY_SECONDS = 2
DEFAULT_MIN_DISK_SPACE_GB = 2.0
